"""AI Agent investigation API router (Phase 5)."""

import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import require_analyst, require_viewer, get_current_user
from app.models.transaction import Transaction
from app.models.audit import AuditLog
from app.models.user import User
from app.models.ai_report import AIReport
from app.schemas.ai import AIInvestigationResponse
from app.services.ai_service import run_ai_investigation, AIServiceError
from app.services.audit_service import record_audit_event

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post(
    "/transactions/{transaction_id}/investigate",
    response_model=AIInvestigationResponse,
    dependencies=[Depends(require_analyst)],
)
async def generate_investigation(
    transaction_id: str,
    regenerate: bool = Query(False, description="Force regeneration by calling the AI service again"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generate or reuse a persisted AI fraud investigation report for a transaction.
    Accessible only to ADMIN and ANALYST roles.
    """
    # 1. Fetch target transaction
    tx_result = await db.execute(
        select(Transaction).where(Transaction.transaction_id == transaction_id)
    )
    transaction = tx_result.scalar_one_or_none()
    if not transaction:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Transaction '{transaction_id}' was not found.",
        )

    # 2. Check if report already exists in DB
    report_result = await db.execute(
        select(AIReport).where(AIReport.transaction_id == transaction_id)
    )
    existing_report = report_result.scalar_one_or_none()

    if existing_report and not regenerate:
        logger.info("Serving cached AI report for transaction %s", transaction_id)
        return AIInvestigationResponse.model_validate(existing_report)

    # 3. Retrieve context data (History + Audits)
    # Fetch customer history
    history_result = await db.execute(
        select(Transaction)
        .where(Transaction.customer_id == transaction.customer_id)
        .order_by(Transaction.created_at.desc())
    )
    # Exclude current transaction from history
    history = [t for t in history_result.scalars().all() if t.transaction_id != transaction_id]

    # Fetch audit logs
    audit_result = await db.execute(
        select(AuditLog)
        .where(AuditLog.transaction_id == transaction_id)
        .order_by(AuditLog.timestamp.desc())
    )
    audit_logs = list(audit_result.scalars().all())

    # 4. Invoke AI agent (will fall back to mock if API key is absent)
    try:
        investigation = run_ai_investigation(transaction, history, audit_logs)
    except AIServiceError as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=str(exc)
        )

    # 5. Persist the report (insert or update)
    if existing_report:
        # Update existing report fields
        existing_report.summary = investigation.summary
        existing_report.key_evidence = investigation.key_evidence
        existing_report.risk_reasoning = investigation.risk_reasoning
        existing_report.recommended_action = investigation.recommended_action
        existing_report.confidence = investigation.confidence
        existing_report.limitations = investigation.limitations
        existing_report.is_mock = investigation.is_mock
        db.add(existing_report)
    else:
        new_report = AIReport(
            transaction_id=transaction_id,
            summary=investigation.summary,
            key_evidence=investigation.key_evidence,
            risk_reasoning=investigation.risk_reasoning,
            recommended_action=investigation.recommended_action,
            confidence=investigation.confidence,
            limitations=investigation.limitations,
            is_mock=investigation.is_mock,
        )
        db.add(new_report)

    # 6. Record audit trail event
    await record_audit_event(
        db,
        event="AI_INVESTIGATION_GENERATED",
        actor=current_user.username,
        transaction_id=transaction_id,
        metadata_={
            "is_mock": investigation.is_mock,
            "recommended_action": investigation.recommended_action,
            "confidence": investigation.confidence
        },
        details=f"AI Investigation report generated by {current_user.username} (mock={investigation.is_mock})."
    )

    try:
        await db.commit()
    except Exception as exc:
        await db.rollback()
        logger.exception("Database commit failed while saving AI report")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to persist the AI report to the database."
        )

    return investigation


@router.get(
    "/transactions/{transaction_id}/investigate",
    response_model=AIInvestigationResponse,
    dependencies=[Depends(require_viewer)],
)
async def get_investigation(
    transaction_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Retrieve an existing AI fraud investigation report for a transaction.
    Accessible to ADMIN, ANALYST and VIEWER roles.
    """
    report_result = await db.execute(
        select(AIReport).where(AIReport.transaction_id == transaction_id)
    )
    report = report_result.scalar_one_or_none()
    if not report:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No AI investigation report exists for transaction '{transaction_id}' yet. Please generate one first.",
        )
    return AIInvestigationResponse.model_validate(report)
